# Generated by Django 3.2.16 on 2023-03-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryform',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='enquiryform',
            name='state',
        ),
    ]
