# Generated by Django 3.2.16 on 2023-03-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_view', '0009_alter_car_description'),
        ('enquiry_form', '0002_auto_20230319_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryform',
            name='car_id',
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars_view.car'),
        ),
    ]
