# Generated by Django 3.2.16 on 2023-02-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_view', '0002_auto_20230213_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Luxury Car', 'Luxury Car'), ('Limited Series', 'Limited Series'), ('Sports Car', 'Sports Car')], max_length=150),
        ),
    ]
