# Generated by Django 3.2.16 on 2023-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_view', '0004_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
