# Generated by Django 3.2.16 on 2023-02-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_view', '0007_alter_car_no_of_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='county',
            field=models.CharField(choices=[('Dublin', 'Dublin'), ('Cork', 'Cork'), ('Limerick', 'Limerick'), ('Galway', 'Galway'), ('Waterford', 'Waterford'), ('Louth', 'Louth'), ('Kilkenny', 'Kilkenny'), ('Wexford', 'Wexford'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Bray', 'Bray'), ('Wicklow', 'Wicklow'), ('Meath', 'Meath'), ('Clare', 'Clare'), ('Kerry', 'Kerry'), ('Carlow', 'Carlow'), ('Kildare', 'Kildare'), ('Westmeath', 'Westmeath'), ('Donegal', 'Donegal'), ('Offaly', 'Offaly'), ('Sligo', 'Sligo'), ('Carlow', 'Carlow'), ('Fingal', 'Fingal'), ('Lois', 'Lois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Mayo', 'Mayo'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('South Dublin', 'South Dublin'), ('Tipperary', 'Tipperary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('V8', 'V8'), ('V10', 'V10'), ('LE3512', 'LE3512'), ('V12', 'V12')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('hybrid', 'hybrid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Aventador', 'Aventador'), ('Huracán', 'Huracán'), ('Urus', 'Urus'), ('Countach', 'Countach'), ('Sián FKP 37', 'Sián FKP 37'), ('Sián Roadster', 'Sián Roadster'), ('Terzo Millennio', 'Terzo Millennio'), ('Asterion', 'Asterion'), ('Estoque', 'Estoque'), ('Huracán GT3 EVO2', 'Huracán GT3 EVO2'), ('Huracán Super Trofeo EVO2', 'Huracán Super Trofeo EVO2'), ('SC18 Alston', 'SC18 Alston'), ('Essenza SCV12', 'Essenza SCV12')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmmision',
            field=models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], max_length=10),
        ),
    ]
