# Generated by Django 3.2.16 on 2023-02-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_view', '0008_auto_20230214_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
