# Generated by Django 3.2.16 on 2023-02-07 19:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('position_name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('facebook_link', models.URLField(max_length=100)),
                ('twiter_link', models.UUIDField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
