# Generated by Django 3.2.16 on 2023-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamborghini_deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='twiter_link',
            field=models.URLField(max_length=100),
        ),
    ]
