# Generated by Django 3.2.16 on 2023-03-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamborghini_deals', '0006_auto_20230319_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_on',
        ),
    ]
